{{ $staticConfig := ""}}
{{- if .Values.controller.staticConfig.configMap }}
  {{- with .Values.controller.staticConfig.configMap }}
    {{- if and .name .key }}
      {{- $data := (lookup "v1" "ConfigMap" $.Release.Namespace .name).data }}
      {{- if hasKey $data .key }}
        {{- $staticConfig = get $data .key }}
      {{- else }}
        {{- fail (cat "ERROR: ConfigMap" .name "with" .key "key cannot be found in" $.Release.Namespace "namespace") }}
      {{- end }}
    {{- else }}
      {{- fail (cat "ERROR: You need to specify both name and key while using configMap for staticConfig") }}
    {{- end }}
  {{- end }}
{{ else }}
{{ $staticConfig = tpl (toYaml .Values.controller.staticConfig.content) . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "traefikee-helm-chart.configname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
data:
  static.yaml:
    {{- $staticConfig | nindent 4 }}
{{- end }}

{{- if not (contains "ping" $staticConfig) }}
  {{- if ($.Values.proxy.readinessProbe).httpGet }}
    {{- if eq $.Values.proxy.readinessProbe.httpGet.path "/ping" }}
      {{- fail "ERROR: Readiness Probe is configured using ping and ping is not enabled in staticConfig" }}
    {{- end }}
  {{- end }}
  {{- if ($.Values.proxy.livenessProbe).httpGet }}
    {{- if eq $.Values.proxy.livenessProbe.httpGet.path "/ping" }}
      {{- fail "ERROR: Liveness Probe is configured using ping and ping is not enabled in staticConfig" }}
    {{- end }}
  {{- end }}
{{- end }}
